### PR TITLE
feat: Instagram and Google gradients

### LINKED ISSUE #79: Instagram and Google Swatches
Implement the  `Swatch` interface for Instagram and Google so that anyone can fetch the color of theses companies at once.

### PR DESCRIPTION
**Pull request by rafamizes**
Closes #79

### CODE REVIEW

**Comment by rafamizes** [comment]
@rultor merge.

**Comment by rafamizes** [comment]
@rultor merge.

**Comment by dartoosdev** [comment]
@rultor merge.

**Comment by rafamizes** [comment]
@rultor merge.

**Comment by rafamizes** [comment]
Closes #79

**Pull request merged**
